### ISSUE TITLE
Installing Narrafirma

### ISSUE THREAD

**Issue by eliza411** [pdfernhout/narrafirma#1]
I'm finally trying my hand at installing Narrafirma. I don't see any detailed install instructions yet, so I'm kind of fumbling around. 

I'm setting up in a Debian-based Docker environment. I'm not trying to containerize Narrafirma or anything, just using a container for [Wordpress and Mariadb via docker-compose](https://hub.docker.com/_/wordpress/).

So far I've:
- Set up Wordpress and Mariadb 
- Copied the `WebContent` directory into the `wordpress-plugin/narrafirma` directory
- Mounted that narrafirma directory in `wp_content/plugins`
- I installed 
  - `npm` for [debian](https://github.com/joyent/node/wiki/installing-node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions), including the `build-essentials`
  -  `bower` and `tsc`
- I copied `tsconfig.json` into the `WebContent` directory since it says it tsc should be run from there
- Realized I'm unclear what goes where and what needs building and started writing this :)
- I did activate Narrafirma 
- I've created a project with these permission:
  `
  {
        "NarraFirmaProject-Sample Project": {
            "write": [
                true
            ],
            "read": [
                true
            ],
            "survey": [
                true
            ]
        }
    }
  `
- When I click "launch the NarraFirma application" I get "Starting NarraFirma; please wait" which makes sense as I think there are things missing. I'm not sure which logs to tail and it's getting late.

If it's helpful to you for me to work on the install directions, I'm happy to continue as I have time available. If it's a distraction, there's certainly no urgency on my part.

**Comment by pdfernhout** [comment]
@eliza411 Melissa- Thanks for talking with Cynthia about NarraFirma and for trying it out. Sounds like you are very close to making it work. Below are some troubleshooting suggestions. Please let me know how you progress on this or if I can be of more help in troubleshooting this (even by Skype if it helps).

If the NarraFirma web application is not getting beyond the "Please Wait" stage in the browser, you could look at the JavaScript console in your web browser and see if it has logged any error messages. If that does not provide an obvious answer (like errors related to specific files not found on the server), you could also look at the Apache logs and see if you are getting any permissions issues or such.

As a first possibility, make sure there are JavaScript files with a js extension under the "js" directory, just to be sure tsc is working as expected in your setup. Even though you installed the TypeScript compiler, you did not mention actually running "tsc" from the command line, which is what generated the JavaScript files in the js directory. In case you did not, the compiler will not run automatically unfortunately -- unless you are doing what I do and developing code in an IDE that supports TypeScript (I'm using Eclipse with the Palantir TypeScript plugin). So, without IDE support (or a packaging script step), tsc needs to be run manually on the command line each time a change is made to the TypeScript source code (including when pulling new versions from GitHub, including the first time).

In general, the TypeScript compiler, "tsc" should look up the directory hierarchy for tsconfig.json. But I'm not sure how tsc behaves when looking up a directory past a symbolic link, so I can imagine that file might have to be copied (or linked to) in such a case (as you did).

For my current testing, I copy the narrafirma plugin directory manually to the WordPress plugin directory after each change for testing. I also made a symbolic link within the plugin directory to the WebContent directory. So, I've been testing with a different setup than yours as far as what files are copied how and with what permissions. I had Apache permissions issues related to file ownership and symbolic links when I had first tried to use an approach similar to what you outlined, using a symbolic link from the WordPress plugin directory to the project code elsewhere on my testing setup (an older Mac). Probably those permission issues and symbolic linking issues could be solved, but I did not prioritize that for now, so copying the files was a straightforward workaround for my specific setup. That kludgy approach I use for copying with rsync is detailed in a README file mentioned in the last paragraph below. There is probably a better way to do this in general that does not entail copying either the WebContent directory (as you did) or the whole plugin directory (as I did).

The NarraFirma project permissions you outlined for a first "Sample Project" project should make the project editable by anyone. That is great for initial testing, but of course you would probably not want to make such a system available to the world other than as a throw-away test system (I'm writing that caution mostly for anyone else reading this in the future with less computer knowledge than you who sees that example).

Also, I don't think I've tested project names with a space in them, so it is possible that could also be an issue -- although I expect that should work.

Improving the WordPress plugin install directions would be great; thanks. Right now, there are some limited directions for the WordPress plugin which you've probably seen in the narrafirma-plugin directory; also linked [here](https://github.com/pdfernhout/narrafirma/blob/master/wordpress-plugin/README-wordpress-plugin.txt). **[Update 2015-08-21: That link no longer works since the file was renamed; an improved version is [here](https://github.com/pdfernhout/narrafirma/blob/master/wordpress-plugin/README.md).]** But they are kind of sketchy at the moment; sorry about that. What is probably needed even more urgently for the WordPress plugin (and is now on the TODO list) is to make some sort of Node.js npm packaging script (ideally [not requiring anything beyond npm](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/)) to make an easily-installed zip file. I don't think it should be more than a dozen lines or so to get npm to do the basics of running tsc and zipping up the results? I plan to work on such a script (or at least an available zip file) by the end of next week, but, beyond better install directions, you're also welcome to do that if you want and have time and interest.

**Comment by eliza411** [comment]
Thanks @pdfernhout!

I was indeed very close at the tail end of a very long day.

I set down to troubleshoot tonight, and it was easy to see the problem. 

I had run the `tsc` command, but with `tsconfig.json` copied inside the WebContent directory, a new WebContent directory was created, resulting in `wp-content/plugins/narrafirma/WebContent/WebContent/js`

I deleted the extra directory, put `tsconfig.json` in the 'narrafirma' directory, ran tsc again, and the files were in the right location.

I need to add the configuration steps to my Dockerfile and test, then I can see about streamlining the  install directions for the Wordpress plugin. I  can also provide the Dockerfile for anyone interested in getting set up that way. I'm sure that the Node.js npm packaging script is probably a better approach for target users, but since I have the Dockerfile working, it's possibly valuable to someone else out there. It's not likely that I'll get so far as looking at the npm things, as that's all brand-new and work has me pretty busy. I can test, though, once you have it.

**Comment by pdfernhout** [comment]
@eliza411 Thanks for the update. Glad to hear about your progress!  A Dockerfile sounds useful; feel free to submit a pull request with one.

When I first wrote the directions for the plugin and copying the WebContent directory, the application was still in plain JavaScript, not TypeScript, so copying that directory would always give you the latest files. Based on your report, I see now that with the move to TypeScript, copying the WebContent directory will only work if someone has first run "tsc" before the copy (or is using an IDEA) so that the "WebContent/js" directory is already filled in with the compiled output. Or, alternatively, as you figured out, you need to copy the tsconfig.json to the wordpress-plugin/narrafirma directory and then run "tsc" within that plugin directory.

So, based on what we have discussed here, I just now updated the WordPress plugin [README file](https://github.com/pdfernhout/narrafirma/blob/master/wordpress-plugin/README.md) to hopefully be clearer about that. I also renamed that file so that it shows up directly when browsing GitHub. Unfortunately, GitHub does not currently seem to have a way to display README files with longer more-specific names for README files. However, feel free to make further improvements to that README file or others and submit a PR.

I also created a separate issue (issue #2) about creating the npm packaging script which I will update as I make progress on it to the point where it can be tested by you or others. I also added a comment there on why the installation process has ended up being more complicated that one might initially think it should be (essentially, from trying to support both WordPress and Node.js, and maybe eventually Drupal).

Eventually, we plan to add NarraFirma to the official WordPress plugin repository, so most WordPress users will be able to install it and upgrade it with a single click rather than build anything from source or copy files manually. I'm not sure how the WordPress repository deals with build steps though, so that is another thing to figure out; I was trying to avoid checking in the derived JavaScript output, but I may have to in that case.

Please let me know if there are any more aspects of this current install issue I can try to help with or if you want to discuss the install process further. Otherwise, if the improvements to the README file seem to address this issue well enough for now, feel free to close this issue and open new ones as they come up.

**Comment by pdfernhout** [comment]
@eliza411 I've made a first-cut at a build script to create a zip file so others will have an easier time than you did as a trailblazer. Thanks again for trying it -- rough edges and all -- as your experience was helpful in figuring out priorities and next steps.

Details on the "npm run build-wp" command are in the [latest comment](https://github.com/pdfernhout/narrafirma/issues/2#issuecomment-133776699) to issue #2. You could post feedback on the command in that issue if you try it.

**Comment by pdfernhout** [comment]
@eliza411 Thanks again for bringing this issue up, as things are much better now with a build script for the WordPress plugin. Install seems to be working OK for both Cynthia and me, and you have reported install success separately (also implied by reports to other issues). Pre-made zip files are also available on the releases page, and more detailed install instructions are on the NarraFirma web site here: https://narrafirma.com/home/setting-up-narrafirma-on-your-local-computer/

So, I am closing this issue. However, I am sure that the install directions and build script could no doubt could continue to be improved. Feel free to open new issues about installation or the build process if new questions or problems become apparent.
