### ISSUE TITLE
css "automatic" for text fields?

### ISSUE THREAD

**Issue by hvgard** [pdfernhout/narrafirma#24]
When there is more than one line of text in a text field it is hard to get an overview of what is on a page as the pane doesn't automatically scale to "show all". At least it would be useful if these multi-line fields show say 5 or 10 lines by default. I'm not a css expert but I think that is the automatic setting.

**Comment by cfkurtz** [comment]
Fixed in commit bfee32bef9a109200e0f5981fc8972edb18c22db. Min height set to 5em. Had not wanted to set this very large before, because the pages become super long; but the opposite problem is not being able to read the stuff you wrote the last time you were there. So a 5-row-minimum text area seems okay. (The default setting in HTML is actually 2 lines.)
