### ISSUE TITLE
Plugin not Loading on Wordpress

### ISSUE THREAD

**Issue by dan-ingot** [pdfernhout/narrafirma#37]
Hi team. I've installed the NarraFirma plugin on a couple WordPress sites to test and it's not loading up the editor. After activating the plugin and navigating to the NarraFirma settings page from the WordPress dashboard, it shows a critical error then changes over to a  blank screen. 

Error Details
=============
An error of type E_ERROR was caused in line 109 of the file /srv/htdocs/wp-content/plugins/narrafirma/narrafirma.php. Error message: Uncaught Error: Call to undefined function NarraFirma\defaultOptions() in /srv/htdocs/wp-content/plugins/narrafirma/narrafirma.php:109
Stack trace:
#0 /wordpress/core/5.8.2/wp-includes/class-wp-hook.php(303): NarraFirma\NarraFirmaSettingsPage->create_admin_page('')
#1 /wordpress/core/5.8.2/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#2 /wordpress/core/5.8.2/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 /wordpress/core/5.8.2/wp-admin/admin.php(259): do_action('toplevel_page_n...')
#4 {main}
 thrown

**Comment by cfkurtz** [comment]
Huh. Line 109 is 

> if (!$this->options) defaultOptions();

(meaning, if no options data structure exists, create a default one). The function "defaultOptions" is in the same file as the function call (narrafirma.php), and the function is defined above the function call, so WP should have no problem finding it (it should not be an "undefined function"). 

From what I read, this error seems to come up when (a) another plugin or theme conflicts with a plugin (though why that should matter I do not know) or (b) the php file itself is not loading properly (as in, some parts are loading after other parts try to call them?).

I suggest, as a first thing to try, disabling all other plugins, then reloading the page (including clearing your browser cache) to see if it's a conflict. 

If that doesn't help, I would try deleting NarraFirma, then re-installing it, in case it somehow installed halfway or something. 

If neither of those things work, let me know and I will try to recreate the error. Maybe it only happens when you have a completely new WP installation. However, since you say you tried it on a few sites and it happened on all of them (and I have never seen this error) I suspect a plugin or theme conflict.

**Comment by dan-ingot** [comment]
Hi Cynthia, thanks for your response and explanation. I have tried installing on another Wordpress install on a default theme (twenty twenty-one) with no other plugins activated and got the same critical error message. The plugin was installed via the 'add new' plugin option as apposed to the upload plugin method so believe the plugin should have installed correctly. 

Is there perhaps an archive of some older versions of the plugin I can try to test with?

**Comment by cfkurtz** [comment]
Dan, thanks so much for reporting this bug. We have now replicated it, and we think we have fixed it. Could you update the NarraFirma plugin to version 1.5.5 and tell me if it works correctly now? 

I still don't understand exactly why this happened, but in the course of ticking off a "to do" item, I recently moved a few lines of code out of the "install" function (in narrafirma.php) into a new "defaultOptions" function, and I called the function from elsewhere in the file as well (including in the "create_admin_page" function). Apparently, however, the "defaultOptions" function was not being loaded when I thought it was, due to . . . how WordPress loads up PHP functions or something. (We are neither of us PHP experts...) We have put things back to the way they were before, and it seems to have fixed the problem. Please let me know if it works for you now.

**Comment by dan-ingot** [comment]
Thanks so much. Glad it turned out to be something relatively simple! Have updated the plugin and that is working for me now. Appreciate your speed in getting that sorted!

**Comment by cfkurtz** [comment]
Very glad to hear it, and sorry for the bother. I will be more careful messing with the PHP in the future!
