### ISSUE TITLE
Survey not loading

### ISSUE THREAD

**Issue by Salishsea86** [pdfernhout/narrafirma#43]
I am working with an existing collection and a story form I created in v1.4 and today (on v1.5.12) edited the story form to add some introductory text.  When I make the form live again I get an error that starts like this....thoughts?

Something went wrong loading the survey questionnaire from the server:
{"status":200,"message":"{\"success\":true,\"statusCode\":200,\"description\":\"Success\",\"timestamp\":\"2022-02-23T23:59:48.542108473Z\",\"detail\":\"latest\",\"currentTimestamp\":\"2022-02-23T23:59:48.539901415Z\",\"latestRecord\":{\"receivedTimestamp\":\"2022-02-23T23:59:15.818377466Z\",\"sha256AndLength\":\"77f652e5aab222fe546059bbcdcde8dd52c082d6e5b6a4428afb13685d5c31eb_30552\",\"topicSHA256\":\"dcf18f0c64d6738237d783de16ac645ef75ac39be94f24b7b869078674bee69c\",\"topicTimestamp\":\"2022-02-23T23:59:15.172000947Z\",\"messageContents\":{\"__pointrel_sha256AndLength\":\"77f652e5aab222fe546059bbcdcde8dd52c082d6e5b6a4428afb13685d5c31eb_30552\",\"__pointrel_trace\":[{\"sentByClient\":\"salishsea86\",\"sentTimestamp\":\"2022-02-23T23:59:15.175000213Z\",\"sentToJournalIdentifier\":\"NarraFirmaProject-RLC Fellowship 2022\",\"sentToURL\":\"https:\\/\\/harvestmoonpni.com\\/wp-admin\\/admin-ajax.php\"},{\"receivedByJournalIdentifier\":\"NarraFirmaProject-RLC Fellowship 2022\",\"receivedByServer\":\"UNFINISHED_SERVER_NAME\",\"senderIPAddress\":\"24.84.168.19\",\"userIdentifier\":\"salishsea86\",\"receivedTimestamp\":\"2022-02-23T23:59:15.818377466Z\"}],\"_topicIdentifier\":\"questionnaires\",\"_topicTimestamp\":\"2022-02-23T23:59:15.172000947Z\",\"change\":{\"RLC Cohort 2022\":{\"elicitingQuestions\":[{\"id\":\"01 Recent action\",\"text\":\"Share an action you took recently related to equity (no matter the scale or outcome).

**Comment by cfkurtz** [comment]
Thank you so much for telling us about this bug! It has been fixed in release 1.5.13. 

What happened was, in two of your choice questions, you had extra blank lines in your available-answers lists. I thought I was trimming out such empty lines, but when I looked at the code that did it, I realized that I had accidentally used the "map" function instead of the "filter" function. Duh. So instead of _removing_ the blank items from the list, I was just setting them to "undefined." That caused the HTML to be malformed (with a "null" where there should have been text), and the browser was rejecting it. This is now fixed.
