### ISSUE TITLE
unable to go live with survey or print survey form

### ISSUE THREAD

**Issue by kymh007** [pdfernhout/narrafirma#47]
Something went wrong loading the survey questionnaire from the server:
{"status":200,"message":"{\"success\":true,\"statusCode\":200,\"description\":\"Success\",\"timestamp\":\"2022-06-02T21:19:10.546154925Z\",\"detail\":\"latest\",\"currentTimestamp\":\"2022-06-02T21:19:10.545521297Z\",\"latestRecord\":null}"}
<img width="1512" alt="Screen Shot 2022-06-03 at 9 19 32 AM" src="https://user-images.githubusercontent.com/106778528/171740805-f7d09db2-1b62-4bd9-8298-e1a3582a7c83.png">
<img width="1512" alt="Screen Shot 2022-06-03 at 9 19 26 AM" src="https://user-images.githubusercontent.com/106778528/171740848-c968f6e6-9167-4949-b5a6-98a8bc2d0b9f.png">
<img width="1512" alt="Screen Shot 2022-06-03 at 9 19 19 AM" src="https://user-images.githubusercontent.com/106778528/171740881-570fe7ff-5f5a-447b-8db1-7315a4357d5f.png">

**Comment by cfkurtz** [comment]
Everybody, we resolved this issue over email. Essentially, they had some kind of mismatch between their story collection and story form (possibly caused by changing the story form after creating the story collection?). Creating a new story collection and assigning the form to it fixed the problem. Thanks for letting us know!
