### ISSUE TITLE
Explore patterns: Remarkable?

### ISSUE THREAD

**Issue by jdevoo** [pdfernhout/narrafirma#48]
Hello Paul, Hello Cynthia,
I am using Narrafirma v.1.6.4 on Node and noticed that the moment I double-click in items in the table, the Remarkable? flag switches from 'unmarked' to 'yes' on its own.
As long as I don't double-click, I can browse the entries and the details below.
I am not able to properly use the state buttons to revert back either - at least display remains on yes for me.
I am using Firefox as a browser.
Perhaps I am using this feature incorrectly.

**Comment by cfkurtz** [comment]
Hi jdevoo, thanks for posting the issue. We think we have replicated and fixed the problem. However, we can only get it to happen on projects that were created before version  1.4.0 (in August of 2019), when the "remarkable" flag was added. _Are_ you working on a project that was created before August of 2019? Because if this is happening with new data, it could be a different problem than the one we found and fixed, and we should keep trying to replicate the issue with a newer project.

(What caused the problem - we think - was a bit of code we wrote to update legacy data back in 2019. It was supposed to add a "remarkable" flag to any pattern that had at least one observation but no "remarkable" flag. A circular interaction was getting set up because we changed the data while the page was being redrawn (which caused the page to redraw, changing the data, and so on). Double-clicking was not the only way to get this cycle going (it could also happen by clicking the arrows under the table), but double-clicking did make it more visible. We have now changed the code so that changes to the datastore can only happen when the user changes the "remarkable" flag by hand. This means that people will have to manually update their legacy data, but at least it won't happen "on its own.")

**Comment by jdevoo** [comment]
Thank you Cynthia! That could well be as I am using the example project which I load from an older export. I will generate an import from the newer version of NarraFirma which I have not done and re-load.

**Comment by cfkurtz** [comment]
Hold on, I have not released the fix yet! I was waiting to hear from you, because I didn't want to put out a fix that wouldn't completely solve the problem. I will put out the new release today. It only takes like ten minutes, but I have to be focused and attentive to do it right, so I'd better have some breakfast first.

**Comment by cfkurtz** [comment]
Okay, the release is out, version 1.6.5 has the bug fix. Thank you again for letting us know about it.

**Comment by jdevoo** [comment]
Thank you!
