### ISSUE TITLE
Deleting test stories?

### ISSUE THREAD

**Issue by eliza411** [pdfernhout/narrafirma#5]
I'm not seeing a way to delete test stories. I see that I can ignore them. It looks like the best way to start clean is to delete the Story Collection and rebuild it using the same form. This doesn't seem so bad for the testing phase, but is that how it's supposed to work or have I missed a permission somewhere?

**Comment by pdfernhout** [comment]
Yes, is is supposed to work that way. There was a design choice to never delete data. Obviously, one can always question if that was a good design choice. :-) 

#### More details

That design choice hopefully does make the system more reliable -- to have essentially an append-only data storage design. The ignore field is conceptually somewhat like databases that mark a row as deleted but don't actually remove the data until a compaction process runs. However, NarraFirma does not have a "compaction" process, so that analogy breaks down there. Items marked to ignore just don't show up in the catalysis reports and some other areas. The only place ignored stories should show up is in the story browser and when exporting a CSV file of stories.

Internally, edits to stories work by layering changes on top of the base survey data (such as adding an ignore field or adding an override for a specific field via adding a triple to the triplestore).

#### TODO items

So, reinterpreting your comment/question in the context of that design decision, NarraFirma has at least these issues and/or missing features (and maybe more):
- The documentation should be better to explain this feature/limitation.
- You can't click a checkbox to hide ignored stories in the review incoming stories page.
- You can't click a checkbox (or similar) to exclude ignored stories from a CSV export.
- You can't at least easily clone a set of stories from one story collection to another within the program without including the ignored ones (to compact the resulting new story collection's contents).

#### Priorities and one more possible todo item

Does that sound like a sensible TODO list as a response to this concern? Are there others we should add within that context? Or is not deleting data just a showstopper in some situations?

I'd agree that at least the first three items there (documentation and checkboxes) are worth doing soon and are easy to do.

For the fourth item, which is a bit harder to do, I'm not yet sure if it is a priority time. it is easy to make new story collections that use the same story form (as you mention), as well as import and export data via CSV into a new story collection. When you have the story data in a CSV file, you can do anything you want to it, whether delete rows or scrub identifying details or whatever. 

However, deleting a story collection still does not delete its data from disk. Also, that deleted story collection data will be downloaded from the server when starting up the client. So, it is not just a disk space issue but also a communications issue if you have story collections around that you don't want. Whether that is a big issue in practice remains to be seen. I'd rather wait a bit and see what further feedback I get on this from more users.

If you absolutely need to delete data from a project for some reason using the current architecture, you could export an entire project's current state, start a new project, and then re-import the edited story data. Then you can "delete" the old project. 

But even that does not delete the data of the old project. :-)  If you create a new project with the same name as the old one, the existing data will become accessible again (as mentioned near the bottom of the WordPress NarraFirma admin screen). 

Also, if you uninstall NarraFirma under WordPress, it still leaves those data table around within WordPress' database. I'd agree this is a debatable choice, because a well-behaved plugin generally should be uninstallable without a trace. I have not made that a priority though -- including because we uninstall and reinstall the plugin so many times during development testing and we generally want to keep using the old data. That was also a bigger issue before we added the export options though. Now that you can easily export all of a project's data, I'd be open to making the uninstaller work differently if there was a big demand for change on that, probably where you could perhaps choose whether to delete all the related tables or not, and the plugin would warn you to export any data first. Such a change might require some other supporting changes to track project tables created in a new table rather than how it is done now.

#### How to really delete data right now

In a worst case where, to really delete data, under WordPress you would need to do it manually from within the WordPress database using a database tool. Each NarraFirma project is stored in a separate WordPress table. That makes it relatively easy for someone with sysadmin skill to delete just that project's data with a SQL "drop table" command. Naturally, that is not an exercise for the typical WordPress user.

To really delete data under Node.js, you would need to delete the directory of the project (under server-data/journals) using "rm" from the command line or whatever.

If you absolutely want to keep the project name the same (like if you've given out the survey URL and still want to use exactly that) as well as delete data during an ongoing project, you could export a project's current state and stories, delete the project both inside and outside the NarraFirma system, and then create a new project with the same name, and import a hand-edited version of the data.

So, there is a way to delete data right now if you really want to do it. Whether we should make deleting data easy to do within the program, I'm not sure. A lot of effort can go into collecting a few hundred real-life stories -- stories that you may never be able to get back ever no matter what you do. I would not want to see someone accidentally delete a story collection only to find out out their backups (if any) were bad. On the other hand, if someone does try to delete data and deletes the wrong project table or directory using low-level tools because it was not easy to do within the program, then that would be unfortunate as well. However, one might expect a higher level of diligence in someone using low-level tools. So, I'm still leaning towards not making deleting data possible within the NarraFirma system -- or even when uninstalling the plugin (that last choice being very debatable).

#### Objectives for going forward

I'm going to leave this issue open for further feedback, and also until at least the first three of those todo items are done (documentation and checkboxes). Some of the text above on how to really delete data should probably also make its way into the help system as part of that first todo item.

Does this explanation sound like it might convince other people? 

Admittedly, this is a different approach than most other tools out there use. I'd suggest living with the ignore field for a while and seeing if it grows on you. :-)

**Comment by pdfernhout** [comment]
Cynthia does not think the checkboxes are needed, so I am deferring them for now. I'm referring this to her for improving the documentation based on what I wrote above.

**Comment by eliza411** [comment]
My question was pretty much about how data deletion works more than how it should work or how I need it to work. I'm looking at the story collection and catalysis portions and wrapping m head around what a workflow might look like. For now, I can use import/export functionality to achieve what I need, starting with a fresh install once I have things the way I want them. The use case for evaluating the software is, of course, very different than the use case for actually doing a project. 

I mostly just wanted to understand how it's intended to work, and now I do. Thanks!

**Comment by cfkurtz** [comment]
I have improved the help on ignoring stories and how to permanently delete a story (using export and import). See commit 55c5eec22f2a4ba4faa281f91ae4412ab60903a0

**Comment by sidneygijzen** [comment]
This thread, especially the reply from @pdfernhout, provided a lot of valuable information today. Thanks! I now have a way to delete all my test projects :-)

I would like to suggest to incorporate the information on how to delete projects (and why it's by design it isn't possible out-of-the-box) in the help somewhere.

**Comment by cfkurtz** [comment]
Good point. I am going to raise a new issue to add this explanation to the help system (in a new "administration" help page or something, so it doesn't confuse people looking for less technical help).

**Comment by cfkurtz** [comment]
I have improved the description of ignoring versus deleting on the "Review incoming stories" help page, and I've added a link to the explanation on the main Help page. That should help.
