### ISSUE TITLE
No response to a scale question represented as far left-hand value

### ISSUE THREAD

**Issue by eliza411** [pdfernhout/narrafirma#7]
Expected Behavior: If a user fills out a form and does not move the slider on a scale question, I'd expect when reviewing the incoming story it would either display a special no response-style value or not display the marker.

Exhibited Behavior: Right now, the scale indicator defaults to the left-hand extreme.

Steps to reproduce: Create a slider question, fill out a survey, then review on the incoming story screen.

Note: The value is blank in a data export, which _is_ what I'd expect.

**Comment by cfkurtz** [comment]
This is done! (abbab63090e0018b418df777b63e38d484b8d2b8) Now sliders have "Does not apply" check boxes (under them) that start out checked (because the slider has no value) and uncheck when the user drags the slider button. If the user decides they want to throw away the value they put in, they can check "Does not apply" again. The checkbox says "Does not apply" by default, but in this commit (9c82bf03c0b8ce53861a9c98970bef741b74c317) I added a way to customize what the checkbox says.
